[project]
name = "ipmanager-django"
description = "Stand-alone IP Manager Service (Django implementation)"
version = "1.0.0-dev"
dependencies = [
    "django",
    "django-umd-lib-style",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-django",
    "ruff",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ipmanager.settings"

[tool.ruff.format]
# Prefer single quotes over double quotes.
quote-style = "single"
exclude = ["manage.py"]
